---
name: "Release"

on:
  push:
    tags:
      - 'v**'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"

      - name: Run tests
        run: make test

      - name: Build Windows
        run: make build-windows

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 12dls.exe
          draft: true
          fail_on_unmatched_files: true
