---
name: "Release"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"

      - name: Run tests
        run: make test

  release:
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"

      - name: Build
        run: go build -o ./12dls.exe ./cmd/12dls

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 12dls.exe
          draft: true
          fail_on_unmatched_files: true
          token: ${{ secrets.TOKEN }}
